apiVersion: v1
kind: Secret

metadata:
  name: application-secret
  namespace: application

type: Opaque

stringData:

  DATABASE_URL: postgresql://exposureops:exposureops@postgres-service:5432/exposureops

  REDIS_URL: redis://redis-service:6379