apiVersion: apps/v1
kind: Deployment

metadata:
  name: api
  namespace: application

spec:
  replicas: 1

  selector:
    matchLabels:
      app: api

  template:
    metadata:
      labels:
        app: api

    spec:
      containers:
        - name: api

          image: exposure-api:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20

          resources:
            requests:
              cpu: 100m
              memory: 256Mi

            limits:
              cpu: 500m
              memory: 512Mi


          env:

            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: application-secret
                  key: DATABASE_URL

            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: application-secret
                  key: REDIS_URL

          envFrom:
            - secretRef:
                name: api-secret