apiVersion: apps/v1
kind: Deployment

metadata:
  name: worker
  namespace: application

spec:
  replicas: 1

  selector:
    matchLabels:
      app: worker

  template:
    metadata:
      labels:
        app: worker

    spec:
      containers:
        - name: worker

          image: exposure-worker:latest
          imagePullPolicy: IfNotPresent

          resources:
            requests:
              cpu: 100m
              memory: 128Mi

            limits:
              cpu: 500m
              memory: 512Mi

          env:

            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: application-secret
                  key: DATABASE_URL

            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: application-secret
                  key: REDIS_URL

            - name: WORKER_PROCESSING_DELAY_MS
              value: "2000"

            - name: WORKER_FAILURE_RATE_PERCENT
              value: "10"

            - name: SCAN_FINDINGS_GENERATION_ENABLED
              value: "true"