apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "exposure.fullname" . }}-worker

spec:
  replicas: {{ .Values.worker.replicaCount }}

  selector:
    matchLabels:
      app: worker

  template:

    metadata:
      labels:
        app: worker

    spec:

      containers:

        - name: worker

          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: IfNotPresent

          env:

            - name: DATABASE_URL
              value: postgresql://exposureops:exposureops@postgres:5432/exposureops

            - name: REDIS_URL
              value: redis://redis:6379