apiVersion: apps/v1
kind: Deployment

metadata:
  name: web
  namespace: application

spec:
  replicas: 1

  selector:
    matchLabels:
      app: web

  template:
    metadata:
      labels:
        app: web

    spec:
      containers:
        - name: web

          image: exposure-web:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5173

          resources:
            requests:
              cpu: 100m
              memory: 128Mi

            limits:
              cpu: 300m
              memory: 256Mi

          env:
            - name: VITE_API_BASE_URL
              value: http://api-service:3000