apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: application
type: Opaque
stringData:
  POSTGRES_USER: exposureops
  POSTGRES_PASSWORD: exposureops
  POSTGRES_DB: exposureops